config/routes.rb
Rails.application.routes.draw do
  get 'admin' => "admin_page#index", as: :admin

  get 'main/index'
  root 'main#index'    
  get 'where-to-sell-silver-nyc-queens' => 'main#contacts', as: :contacts    
  get 'info-:second_title' => 'main#show_post', as: :show_post
  get 'about-sell-silver-nyc' => 'main#about', as: :about    
  post '/message' => 'main#message' , as: :message  
  get 'messages' => 'main#messages'
  get 'how-do-we-buy-sylver-in-nyc' => 'main#how_it_works', as: :how_it_works    

end

app/models/content.rb
class Content < ActiveRecord::Base
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/param.rb
class Param < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/admin_page_controller.rb
class AdminPageController < ApplicationController
  layout "admin"
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
        
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  
  before_action :create_message_obj
    
  def create_message_obj
    @message = Message.new
    @posts = Post.all.first(5)
    @title = "Sell Diamonds And Jewelry In NYC | Queens | Top Dollar For Your Diamonds"  
  end      
    
  def contacts
      
  end
      
  def about  
  end      
    
  def how_it_works 
  end      
    
  def message
     msg = params[:message] 
     @message = Message.new(
         :name => msg[:name],
         :phone_number => msg[:phone_number],
         :email => msg[:email],
         :message => msg[:message]
         )
      
     if verify_recaptcha(model: @message) && @message.save
        flash[:success] = "Message has been sent"
     else
        flash[:error] = "Message has not been sent"
     end     
      
     redirect_to root_path 
  end      
    
  def messages
        render :json => {"messages" => Message.all}
  end      
    
  def index
      
  end
    
  def show_post
     @post = Post.where(["second_title = ?", params[:second_title]]).first 
     @title = @post.url
  end      
end

app/helpers/admin_page_helper.rb
module AdminPageHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    def get_content_by_name name
       result = ""
       unless Content.find_by(name: name).nil?
         result =Content.find_by(:name => name).content 
       end 
        result
    end       
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/admin_page/index.html.erb
<h1>AdminPage#index</h1>
<p>Find me in app/views/admin_page/index.html.erb</p>

app/views/layouts/_diamond_table.haml
%table.table.table-striped.table-bordered
  %tr
    %th
      = "Element"
    %th
      = "Effect on Value"
    %th
      = "Description"
  %tr
    %td
      = "Size"
    %td
      = "Refers to the carat weight. The larger the stone the better, when it comes to resale value."
    %td
      = "The closer you are to a weight threshold, i.e. 0.50 cts or 1.00 cts, the better the cut needs to be. Once you pass a magic size, the price per carat increases. For example, a 1.00 ct stone is worth approximately 15-20% more per carat than a 0.90 ct stone."
  %tr
    %td
      = "Shape"
    %td
      = "The contours and outlines of a diamond have a significant impact on its appearance. Rounds are more valuable than fancy shapes such as: cushions, princess cuts, radiants and asschers."
    %td
      = "Fashion dictates the popularity and therefore the value of a particular shape."
  %tr
    %td
      = "Color"
    %td
      = "A diamond’s color grade is based on its depth of color, and ranges from D-Z, with D being the most valuable color."
    %td
      = "Fancy colors are even more valuable than D color with reds, blues and greens being the rarest and therefore the most sought after."
  %tr
    %td
      = "Clarity"
    %td
      = "Refers to the absence of inclusions and blemishes. The more clarity characteristics (inclusions) a diamond has, the lower it will score on the clarity grade and the lower the value."
    %td
      = "Does the diamond look clear to the naked eye or not? Imperfections may not be visible to the naked eye, however if they are, this represents a significant inclusion."   
  %tr
    %td
      = "Fluorescence"
    %td
      = "The light emitted by diamonds when exposed to ultraviolet light."
    %td
      = "Fluorescence can actually be moderately positive for the value of diamonds with I or lower color. Diamonds with Very Strong Blue Fluorescence typically fetch 30% less than stones with no fluorescence."  
  %tr
    %td
      = "Cut"
    %td
      = "A diamond’s cut grade refers to how well a diamond’s facets interact with light. The cut impacts a diamond’s brilliance and sparkle."
    %td
      = "Only rounds are given cut grades by the GIA."
  %tr
    %td
      = "Polish"
    %td
      = "Refers to the overall smoothness and condition of the facets or surface of the diamond."
    %td
      = "A triple EX grade (i.e. EX cut, EX polish and EX symmetry) is generally worth 7-10% more than a triple VG grade."
  %tr
    %td
      = "Symmetry"
    %td
      = "Symmetry refers to the exactness of shape, overall outline, placement and alignment of individual facets."
    %td
      = "The more symmetrical the stone, the higher the price it can reach." 
      

app/views/layouts/_footer.haml
%hr
%footer.footer-distributed
  .footer-left
    %h3 
      %span 
        = get_content_by_name("full_website_name")
    %p.footer-links
      = link_to "Home", root_path
      ·
      = link_to "About", about_path
      ·
      = link_to 'Contacts', contacts_path
    %p.footer-company-name WeBuyGoods.Com © 2016
  .footer-center
    %div
      %i.fa.fa-map-marker
      %p
        %a{:href => "https://www.google.com/maps/dir/Current+Location/8710+Lefferts+BLVD+Richmond+Hill+NY+11418"}
          %span Queens: 119-16 Jamaica Ave
          Jamaica, NY 11418
    %div
      %i.fa.fa-phone
      %p
        %a{:href => "tel:#{get_content_by_name("company_phone_number")}"} 
          = get_content_by_name("company_phone_number")
    %div
      %i.fa.fa-envelope
      %p
        %a{:href => "mailto:#{get_content_by_name("company_email_address")}"} 
          = get_content_by_name("company_email_address")
  .footer-right
    %p.footer-company-about
      %span 
        = get_content_by_name("footer_about_site")
      = get_content_by_name("footer_about_short_description")
    .footer-icons
      %a{:href => "https://www.facebook.com/webuygoodsnyc"}
        %i.fa.fa-facebook
      %a{:href => "https://plus.google.com/106507584776418285314/about"}
        %i.fa.fa-google-plus
      %a{:href => "https://www.instagram.com/webuygoodsnyc/"}
        %i.fa.fa-instagram
      %a{:href => "https://twitter.com/webuygoodsnyc"}
        %i.fa.fa-twitter

app/views/layouts/_navbar.haml
/ Navigation
%nav.navbar.navbar-inverse.navbar-fixed-top{:role => "navigation"}
  .container
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "/"} 
        = get_content_by_name("full_website_name")
    / Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li
          %a{:href => "/"} Home
        %li
          = link_to "How it works?", how_it_works_path
        %li
          = link_to "About", about_path
        %li
          = link_to "Contacts", contacts_path
      %ul.footer-icons.nav.navbar-nav.navbar-right.hidden-xs
        %li
          %a{:href => "https://www.facebook.com/webuygoodsnyc"}
            %i.fa.fa-facebook
        %li  
          %a{:href => "https://plus.google.com/106507584776418285314/about"}
            %i.fa.fa-google-plus
        %li
          %a{:href => "https://www.instagram.com/webuygoodsnyc/"}
            %i.fa.fa-instagram
        %li
          %a{:href => "https://twitter.com/webuygoodsnyc"}
            %i.fa.fa-twitter
    / /.navbar-collapse
  / /.container
%a#phone-button-wrapper.visible-xs{:href => "tel:+1-718-846-1600"}
  %i.fa.fa-phone.fa-2x
.call-now-sign.visible-xs
  call now
.flash-wrapper.col-lg-8.col-lg-offset-2
  - flash.each do |key, value|
    %div{:class => "#{key}-wrapper"}
      = value 
  
  

app/views/layouts/_sidebars.haml
/ Blog Sidebar Widgets Column
.col-md-4
  / Blog Search Well
  .well.hidden-xs
    %h4 Contacts:
    %h5 
      %a{:href => "tel:+1-718-846-1600"} +1 (718) 846-1600
    %h5 
      %a{:href => "mailto:webuygoodsny@gmail.com"} webuygoodsny@gmail.com
    / /.input-group
  / Blog Categories Well
  .well
    .row
      .col-lg-12.text-center
        %h3 NYC Diamond Buyers
      .col-lg-6.col-xs-6
        = image_tag "/s-1.jpeg", class: "img-responsive"
      .col-lg-6.col-xs-6
        = image_tag "/s-2.jpeg", class: "img-responsive"
  .well
    %h4 Info:
    .row
      .col-lg-12
        %ul.list-unstyled
          - @posts.each do |post|
            %li
              = link_to "#{post.second_title}", show_post_path(post.second_title)
        
      / /.col-lg-6
    / /.row
  / Side Widget Well
  .well
    %h4 Send Message
    = form_for(@message, url: message_path) do |form|
      .form-group
        = form.label :name
        = form.text_field :name, class: "form-control"
        = form.label :email
        = form.text_field :email, class: "form-control"
        = form.label :phone_number
        = form.text_field :phone_number, class: "form-control"
        = form.label :message
        = form.text_area :message, class: "form-control"
        %br
        = recaptcha_tags site_key: "6LdoFw8UAAAAAFr-16_Ydc9JjYpPEDwlmAbeEUxX"
        %hr
        = form.button 'send message', class: "btn btn-info"
/ /.row

app/views/layouts/admin.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %meta{:content => "", :name => "description"}/
    %meta{:content => "", :name => "author"}/
    %title
      = @title
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    / HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries
    / WARNING: Respond.js doesn't work if you view the page via file://
    /[if lt IE 9]
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  %body
    = render '/layouts/admin_navbar'
    .container
      .row
        .col-md-12
          = yield

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %meta{:content => "Highest cash for Diamonds in New York City. If you looking for a safe place to sell your diamonds and jewelry we are here for you. Top dollar for diamonds and jewelry in NYC | Queens | Bronx | Brooklyn | Long Island etc", :name => "description"}/
    %meta{:content => "Sell, Diamonds, Diamonds, Jewelry, Cash, Engagement Ring, Pawn, Earrings, Ring, Rings, Stones, Gold, Silver, Necklace, NYC, Bronx, Brooklyn, Manhattan, Staten Island", :name => "keywords"}/
    %meta{:content => "", :name => "author"}/
    %title
      = @title
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    / HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries
    / WARNING: Respond.js doesn't work if you view the page via file://
    /[if lt IE 9]
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  %body
    = render '/layouts/navbar'
    .container
      .row
        .col-md-8
          = yield
        = render '/layouts/sidebars'
    =render '/layouts/footer'

app/views/main/about.haml
%h1.page-header 
  = get_content_by_name("about_page_h1_tag")
%h2
  %span 
    = "About #{get_content_by_name("full_website_name")}"
%p.lead
  = get_content_by_name("about_page_text")
  %span 
    = get_content_by_name("about_page_text")
%hr
%img.img-responsive{:alt => "#{get_content_by_name("about_img_alts")}", :src => "#{get_content_by_name("about_img_path")}"}/
%hr

app/views/main/contacts.haml
%h1.page-header
  = get_content_by_name("contacts_page_h1_tag")
  %br
  %small 
    = get_content_by_name("contacts_page_h2_tag") 
%h3 Contacts:
%h5 
  = "tel: #{get_content_by_name("company_phone_number")}"
%h5 
  = "email: #{get_content_by_name("company_email_address")}"
%hr
%p 
  = get_content_by_name("contacts_page_description")
- if true 
  .col-lg-12.col-md-12.col-sm-12.col-xs-12
    %h3.text-center Queens Location:
    %p.map-images
      %iframe{:width=>"100%", :height=>"250", :align => "center" ,:frameborder=>"0" ,:style=>"border:0", :src=>"https://www.google.com/maps/embed/v1/place?q=119-16%20Jamaica%20Ave%20Queens%2C%20New%20York%2C%20NY%2C%20United%20States&key=AIzaSyAG1JHhDDpKIublp2o1A107YHnRFEGQa7E"}
- if false
  .col-lg-12.col-md-12.col-sm-12.col-xs-12
    %h3.text-center Queens Location 
    %p.map-images
      %iframe{:width=>"100%", :height=>"600" , :align => "center" , :frameborder=>"0" ,:style=>"border:0", :src=>"https://www.google.com/maps/embed/v1/place?q=8710%20Lefferts%20Blvd%2C%20Richmond%20Hill%2C%20NY%2C%20United%20States&key=AIzaSyAG1JHhDDpKIublp2o1A107YHnRFEGQa7E"}
%br
%hr
%h3.text-center We are open every day from 10 am till 6 pm      

app/views/main/how_it_works.haml
%h1.page-header
  How do we buy silver in NYC?
  %br
  %small How do we buy silver? 
  %h2
    %span 
      = "How Are Diamonds valued?"
  %p.lead
    %span 
      = "Before you can sell your diamond jewelry, you need to have an idea what its value is. Every element of a diamond affects its worth. Examining the condition of a used diamond is a key component in determining its value."
  %p.lead
    %span
      = "We have outlined below the major factors that our buyers take into consideration when appraising diamonds. These highlighted qualities strongly influence your gem’s value and help estimate how much your diamond is worth."
  %hr
    = render "/layouts/diamond_table"    
  %p.lead
    %span
      = "After reviewing the above table, the final step is to consider where you will be selling your used diamond. The retail price you originally paid is not the same as the wholesale value of your piece. Like most assets, diamonds, once purchased, depreciate in value. However, some diamonds acquired many years ago may have increased in value. Should you decide to exchange your diamonds for cash, contact us and you will receive unmatched service from our trusted staff."
  %img.img-responsive{:alt => "", :src => "/ph.jpg"}
%hr

app/views/main/index.haml
/ Page Content
/ Blog Entries Column
%h1.page-header
  Sell Your Diamonds and Jewelry
  %br
  %small Diamonds Buyers of NYC | Queens | Bronx | Brooklyn
/ First Blog Post
- @posts.first(5).each do |post|
  %h2
    %span 
      = post.title
  %p.lead
    %span 
      = post.second_title
  %hr/
  %img.img-responsive{:alt => "#{post.img_alt}", :src => "/#{post.img_url}"}/
  %hr/
  %p 
    = post.description
  = link_to "Read More", show_post_path(post.second_title) ,class: "btn btn-primary"
%hr
- unless Content.find_by(:name => "index_page_under_posts").nil?
  %p
    = Content.find_by(:name => "index_page_under_posts").content
- unless Content.find_by(:name => "index_page_under_post_2").nil?
  %p
    = Content.find_by(:name => "index_page_under_post_2").content
  

app/views/main/show_post.haml
%h1.page-header
  We Buy:
  %br
  %small Silver Coins | Silver Jewelry | Silver
/ First Blog Post
%h2
  %span 
    = @post.title
%p.lead
  %span 
    = @post.second_title
%hr/
%img.img-responsive{:alt => "", :src => "/#{@post.img_url}"}/
%hr/
%p.description-wrapper 
  = @post.description
%hr    
%p 
  = @post.post_body    
%hr